### ISSUE TITLE
Cloud Native AI Working Group - content update instructions

### ISSUE THREAD

**Issue by ronaldpetty** [cncf/tag-runtime#108]
I noticed the page https://tag-runtime.cncf.io/wgs/cnaiwg/ is missing our contact information still (slack channel mainly). I went to add it and found some funky looking markdown (new to me that is). Is there a guide on how to add content (aside fork).

**Comment by ronaldpetty** [comment]
<img width="1791" alt="image" src="https://github.com/cncf/tag-runtime/assets/1390435/f937a628-ba1c-41d9-ab90-bf0183f64b7a">

If you click edit and fork, you see

<img width="1792" alt="image" src="https://github.com/cncf/tag-runtime/assets/1390435/444877f8-1577-4b14-82aa-382bce7c52d0">

Not sure what that syntax is (or where is the page content -- which is just a link to the charter).

**Comment by raravena80** [comment]
This PR https://github.com/cncf/tag-runtime/pull/119 adds content to the page
