### ISSUE TITLE
Virtual Kubelet Incubation assessment and recommendation

### ISSUE THREAD

**Issue by raravena80** [cncf/tag-runtime#12]
Review and assess [Virtual Kubelet](https://github.com/virtual-kubelet/virtual-kubelet) Incubation and make a recommendation to the TOC.

TOC PR: https://github.com/cncf/toc/pull/296

**Comment by rbitia** [comment]
I'll be presenting! Thanks

**Comment by raravena80** [comment]
Update from TOC PR: https://github.com/cncf/toc/pull/296#issuecomment-601416396

**Comment by k82cn** [comment]
Here's the doc on what VK is: https://docs.google.com/document/d/1L8u23UP0wL_V0rNxl7sWsANsv9Y86cuQWn1S2YvldII/edit :)

**Comment by raravena80** [comment]
Closing old issue. Re-open if re-applying for incubation
