### ISSUE TITLE
Create an initial CNAI landscape

### ISSUE THREAD

**Issue by zanetworker** [cncf/tag-runtime#124]
The Cloud Native AI landscape is a project that aims to provide a comprehensive overview of the cloud native AI ecosystem. 

The goal of the landscape is to build it up to a minimal level of usefulness and then merge it into the CNCF landscape as a group. More information about the CNCF landscape is available at https://landscape.cncf.io/. 

- The landscape is being developed by a community of volunteers.
- The landscape is open to contributions from anyone.
- The landscape is licensed under the Apache License 2.0.

@ronaldpetty

**Comment by ronaldpetty** [comment]
I am commenting here so I look less like a bot :)

**Comment by ronaldpetty** [comment]
https://github.com/rx-m/cnai-landscape

https://rx-m.github.io/cnai-landscape/?group=cnai
