### ISSUE TITLE
Create an LLM News Summariser 

### ISSUE THREAD

**Issue by zanetworker** [cncf/tag-runtime#127]
**Executive Summary**

- For CNCF Community: promote AI education and recognize community member participation and become CNCF ambassadors. Drive community visibility, and match challenges and solutions.
- For Companies that work on CNCF AI projects: recognize their community contribution in a tangible way by promoting their open source technologies news

More details here: https://docs.google.com/document/d/1L-gP001biKswpLTX6X0iC2QfLZHBESPpa-VA3KfbhXU/edit

**Comment by zanetworker** [comment]
Progress made here: https://github.com/cncf-tags/cloud-native-ai/tree/main/cncf-youtube-channel-summarizer

**Comment by rootfs** [comment]
The project is closed. The github action and github pages are finished. But due to the github action runtime limitation, the summarization cannot be finished in 6 hours. We will look for additional hosting opportunities.

**Comment by rootfs** [comment]
@zanetworker can you close this issue? thanks

**Comment by raravena80** [comment]
@rootfs changed status to 'done' and closing

**Comment by ronaldpetty** [comment]
If this is done maybe we can demo it and archive ticket?
