### ISSUE TITLE
Quay Incubation review 

### ISSUE THREAD

**Issue by raravena80** [cncf/tag-runtime#16]
TOC PR: https://github.com/cncf/toc/pull/386

**Comment by dmueller2001** [comment]
@raravena80 do you have a date/time for a presentation from projectquay team to SIG Runtime yet schedule?

**Comment by raravena80** [comment]
@dmueller2001 we don't have a time yet. It can be scheduled for any of the upcoming SIG-Runtime meetings. We have upcoming meetings on April 2nd and on April 16th: https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit

**Comment by dmueller2001** [comment]
added Project Quay Incubation Proposal to May 7th SIG-Runtime Agenda

**Comment by raravena80** [comment]
DD draft doc available here: https://bit.ly/quay-dd-document

**Comment by nikhita** [comment]
@raravena80 is this issue still relevant?

**Comment by raravena80** [comment]
@nikhita we can close it.  We haven't heard from the project members for more than 2 years.  We can re-visit if they come back. Thanks!
