### ISSUE TITLE
Update CN AI WG logo on the charter doc and web page

### ISSUE THREAD

**Issue by raravena80** [cncf/tag-runtime#180]
Need to add the logo [here](https://github.com/cncf/tag-runtime/blob/main/wgs/cnai/charter/index.md)

Also the [main web page](https://tag-runtime.cncf.io/wgs/cnaiwg/)

Logo

![CN AI WG Logo](https://github.com/user-attachments/assets/a9910f14-a49a-4047-86df-d20e62876e91)

**Comment by zanetworker** [comment]
I will be updating the charter with https://github.com/cncf/tag-runtime/issues/178, will add it there.
