### ISSUE TITLE
Bug: https://tag-runtime.cncf.io "Mailing List" link points to "group not found" page

### ISSUE THREAD

**Issue by jpmcb** [cncf/tag-runtime#195]
When on https://tag-runtime.cncf.io/, the "Mailing List" link, which seems to point to `https://lists.cncf.io/g/cncf-runtime/topics` redirects to `https://lists.cncf.io/static/groupnotfound` which only looks to have:

```
Sorry, but that group does not exist. 
```

---

What's the right link for the mailing lists? Happy to update this if someone points me to the right link 😅

**Comment by raravena80** [comment]
@jpmcb thanks for raising it!

**Comment by jpmcb** [comment]
/assign

Quick fix in #196 !!!
