### ISSUE TITLE
Use a transcribe tool like otter.ai for our meetings

### ISSUE THREAD

**Issue by raravena80** [cncf/tag-runtime#23]
Following SIG-Security steps: https://github.com/cncf/sig-security/issues/314. It would be nice to have a tool like https//otter.ai for our meetings like @timfong888 [mentioned](https://github.com/cncf/sig-security/issues/314#issuecomment-638341267).

**Comment by amye** [comment]
Zoom will give us an automatic transcript, it just won't be live.

**Comment by raravena80** [comment]
@amye it would be great to post the Zoom transcripts somewhere. Thx!

**Comment by amye** [comment]
That is actually the question - where would be these be posted? in this repo or on YouTube?

**Comment by raravena80** [comment]
I'm not sure if YouTube has a place to post CC transcripts from Zoom(?). They do show up when you click on CC while watching the video. The GitHub repo is alternative but I don't think there's a Zoom transcript integration with GitHub, so that would mean more work creating that integration.

Using something like https://otter.ai is a bit different because a tool like that provides more like actual meeting notes, which would be more comparable to a meeting scribe.

My initial thought behind this was to add a link for [meeting notes](https://bit.ly/cncf-sig-runtime-meeting-notes) under the meeting agenda for every meeting, but I suppose if we can figure how to put a link to the CC content under the agenda is good too (I see that Zoom does provide a link to the transcript of every recorded meeting)

**Comment by yeelinglam** [comment]
Has anyone tried scribbl.co?  It's supposed to be real-time.

**Comment by raravena80** [comment]
@yeelinglam I haven't tried scribbl.co but it also seems like a viable alternative.

**Comment by raravena80** [comment]
Closing this as zoom already has transcription.
