### ISSUE TITLE
TAG Runtime gets a logo

### ISSUE THREAD

**Issue by amye** [cncf/tag-runtime#35]
Options abound! 
Want to discuss in next TAG Runtime meeting, @raravena80? 
[cncf-TAG-runtime-logos.pdf](https://github.com/cncf/tag-runtime/files/6888624/cncf-TAG-runtime-logos.pdf)

**Comment by raravena80** [comment]
@amye sure!  

I've added it to the [agenda](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk).

I'm leaning towards the yellow cheetah, but let's discuss 😄

**Comment by lumjjb** [comment]
I like the 2nd column 3rd row! However, i do like1st column 2nd row  as well and then all the TAGs can have animal mascots and we can do a huge logo together with all the TAGs :).

- R. Racoon

**Comment by dfeddema** [comment]
I like the top right logo (second column first row) - this one looks more like a cheetah than the other cat logos.  My East African expert (aka husband) concurs.   I also like the horse logo, second column bottom right, but the horse should be galloping.

**Comment by raravena80** [comment]
@ebcarty that sounds great.  @RenaudWasTaken @alena1108 can you vote here? 😄 

My vote is for 3 and 6. 1-3 look a lot like Puma or Slazenger to me. Horse sounds like galloping and not running and dog is slower than a Chetah.

**Comment by LiamRandall** [comment]
I like #2, then #1.

I think for branding purposes and uses in printing, etc, a logo should look good in a basic two color.

**Comment by alena1108** [comment]
My vote is for 3, and then 2

**Comment by ebcarty** [comment]
Updated counts to reflect recent votes - feels like the first 3 logos are preferred, maybe we can do a combination of 3 and 2?

Thank you to the team member who pieced the initial logos together.

**Comment by raravena80** [comment]
@amye is it possible to create one with 2 and 3 combined?  The colors of 2 and the horizontal lines of the cheetah in 3 going 'fast'. Thx!

**Comment by elezar** [comment]
I would lean towards 2. Adding the colouring from 3 would make it clearer that it's a cheetah.

**Comment by amye** [comment]
[cncf-TAG-runtime-logos-v2.pdf](https://github.com/cncf/tag-runtime/files/7227177/cncf-TAG-runtime-logos-v2.pdf)
A few more options!

**Comment by ebcarty** [comment]
Thank you Amye for sharing the new logos!
I added letters to each of the new ones to hopefully help tally the votes 🗳️...

<img width="500" alt="2021-09-24_09-31-01" src="https://user-images.githubusercontent.com/13952816/134710582-557d595a-6d18-4088-9c32-4df6f9885e70.png">

**Comment by raravena80** [comment]
I vote for B 😄

**Comment by raravena80** [comment]
@amye I think B may be the winner 😄  let's give it another 2 days if we don't have any more votes then we can settle on B.

**Comment by amye** [comment]
Y'all have a meeting this week, discuss it there?

**Comment by raravena80** [comment]
The group has decided to go with 'C' (most votes) after the meeting on 11/21/2021

**Comment by raravena80** [comment]
nvm.  The logos are int he artwork repo: https://github.com/cncf/artwork/tree/master/other/tag-runtime
