### ISSUE TITLE
KEDA Graduation Review / Presentation

### ISSUE THREAD

**Issue by tomkerkhove** [cncf/tag-runtime#53]
I'm opening this issue to track the KEDA Graduation review/presentation for https://github.com/cncf/toc/pull/925.

**Comment by tomkerkhove** [comment]
I will add a proposal to the meeting schedule in the next couple of days

**Comment by tomkerkhove** [comment]
It looks like this Thursday is too fast for me and every 3rd Thrusday of the month does not work for me so that would be April 6th then - Thoughts @raravena80?

**Comment by nikhita** [comment]
> It looks like this Thursday is too fast for me and every 3rd Thrusday of the month does not work for me so that would be April 6th then

@tomkerkhove we've scheduled one-offs in the past whenever needed. Does March 23rd or 30th work for you? Otherwise we could definitely do April 6th 👍

**Comment by tomkerkhove** [comment]
Sorry for the late reply - Unfortunately not as I have to watch my kids or have an appointment (EU-based) unless the meeting is later during the day. (ie I can do 10 PM PST on 30th for example)

**Comment by raravena80** [comment]
@tomkerkhove can you do 9 PM PT on March 30th? 10 PM is a bit late for me.

**Comment by tomkerkhove** [comment]
Oh sorry, I actually meant 10 PM CEST which is 1 PM PST. Does that work?

> Also, whatever time we schedule the meeting, could you also see if other community members can join, to make it an interactive session?

From KEDA community or in general? The timing might be a pain here from a EU standpoint so we might just as well go with a later date. (and I just noticed I'm on holiday on April 6th) #schedulingpain

What about Tuesday 21st of March at 8 AM PST?

**Comment by zroubalik** [comment]
I can join as well.

**Comment by tomkerkhove** [comment]
Can you join one of the regular upcoming meetings @zroubalik? otherwise we should look at Tuesday 21st of March at 8 AM PST if that works for the TAG.

**Comment by zroubalik** [comment]
I can't join tomorrow (I have a conflict), but in general I can join the regular call. Tuesday 21st of March at 8 AM PST works for me.

**Comment by tomkerkhove** [comment]
Unfortunately I have private appointments then, can you make it @zroubalik ?

**Comment by zroubalik** [comment]
I can join Tuesday 21st of March at 8 AM PST

**Comment by nikhita** [comment]
> I can join Tuesday 21st of March at 8 AM PST

@zroubalik 21st March is already over 😄

**Comment by tomkerkhove** [comment]
I think @zroubalik meant the 28th 😅

**Comment by tomkerkhove** [comment]
Actually, I can join 28th as well but might be a few minutes late.
Does that still work for you @nikhita & @raravena80?

**Comment by raravena80** [comment]
Actually, 03/28 I can do 30 minutes will that work? If we need the full hour 3/30 works better.  Not sure if it works for @nikhita and/or @helayoty.

**Comment by nikhita** [comment]
>  Not sure if it works for @nikhita and/or @helayoty.

Unforunately, I have a conflict on 03/28 but please don't block on me!

**Comment by zroubalik** [comment]
> > I can join Tuesday 21st of March at 8 AM PST
> 
> @zroubalik 21st March is already over 😄

Yeah I meant Mar 28, sorry for the confusion

**Comment by tomkerkhove** [comment]
Let's do March 28th then, 30 min should be perfect for an update.

Shall I send a meeting invite or how does this typically get scheduled?

**Comment by tomkerkhove** [comment]
Thank you for taking the time to talk to us!
- Slides: https://docs.google.com/presentation/d/1A9PkpM7Q6gbzmfHv_YMiUlCizXUnyhKhezDvGiLnfS8/edit?usp=sharing
- Security Audit: https://github.com/trailofbits/publications/blob/master/reviews/2023-01-keda-securityreview.pdf?rgh-link-date=2022-09-14T11%3A10%3A21Z
