### ISSUE TITLE
Notify TAG-Runtime related projects of the switch from  k8s.gcr.io to registry.k8s.io.

### ISSUE THREAD

**Issue by raravena80** [cncf/tag-runtime#54]
Relevant github issue: https://github.com/kubernetes/k8s.io/issues/4780

Need to notify projects of the registry endpoint changes.

**Comment by helayoty** [comment]
Do we have a list of projects that we need to reach out to?

**Comment by raravena80** [comment]
@helayoty, here's a list that we can start with (Graduated, Incubating):

- [Containerd](https://containerd.io/)
- [CRI-O](https://cri-o.io/)
- [KubeEdge](https://kubeedge.io/en/) 
- [Harbor](https://goharbor.io/)
- [KEDA](https://keda.sh/)
- [Knative](https://knative.dev/)
- [Volcano](https://volcano.sh/)

Thanks!

**Comment by raravena80** [comment]
@helayoty can we close this? Thx.

**Comment by raravena80** [comment]
Closing this, given the thumbs up.
