### ISSUE TITLE
WASM Working Group

### ISSUE THREAD

**Issue by helayoty** [cncf/tag-runtime#58]
Recently, we're talking with different communities on how to support WASM (WebAssembly) in the cloud-native environment; and we found it's necessary to align different implementations with specifications.

So I'd like to propose a new working group for WASM and build related specifications for the community.

I'll draft a proposal with more detail on that working group; if any more comments, please let me know.

**Comment by technosophos** [comment]
This is a great idea. Fermyon would be happy to help out however we can.

**Comment by salaboy** [comment]
I am in too ! Great idea

**Comment by bplasmeijer** [comment]
Awesome 👍

**Comment by Mossaka** [comment]
Count me in!

**Comment by autodidaddict** [comment]
Late to the game on this one but I'm very interested.

**Comment by caniszczyk** [comment]
+1 would love to see this

@helayoty I'd love help getting the Wasm landscape out of alpha state too! https://landscape.cncf.io/wasm

If this WG can help with that... THAT WOULD BE AWESOME :)

**Comment by SwEngin** [comment]
Count me in🙂

**Comment by mouismail** [comment]
Count me in please 🚀

**Comment by rchaganti** [comment]
I would love to be a part of this. I have been learning and exploring ways to transform applications to use WASM. It would be great to be a part of this WG and shape this.

**Comment by hannibalhuang** [comment]
count me in as well, our team has been recently experimenting with wasm+sql. Shall we have a get-together at AMS ?

**Comment by shivaylamba** [comment]
I am in! 
This is going to be amazing

**Comment by mikhail-sakhnov** [comment]
I'd love to join the working group since we have plans to use wasm at github.com/k0sproject/k0s

**Comment by mcruzdev** [comment]
I am in too 🚀

**Comment by someshkoli** [comment]
Count me in 🥂

**Comment by Azanul** [comment]
I'm on board, like a surfer ready to catch a wave!

**Comment by nilslice** [comment]
We at Dylibso would love to help out!

**Comment by 0xE282B0** [comment]
Awesome Idea, I'm super interested!

**Comment by squillace** [comment]
Happy to be involved if I can help!

**Comment by fmuyassarov** [comment]
Happy to be involved and offer help!

**Comment by voigt** [comment]
Great initiative, very interested to contribute!

**Comment by Angelmmiguel** [comment]
Great idea! We at Wasm Labs would be happy to help :)

**Comment by verma-kunal** [comment]
Hey all, i heard about the announcement of this working group in the Kubecon EU keynote today & would love to join and help out as well, in any way i can :)

**Comment by Iceber** [comment]
great idea! I am in too🚀

**Comment by rakshitgondwal** [comment]
Count me in! This is going to be amazing:rocket:

**Comment by Rishit-dagli** [comment]
This is awesome! I would love to be a part of this, please count me in 🚀

**Comment by helayoty** [comment]
Many thanks, everyone, for your interest.  The next step for us is to start creating a charter (draft can be found [here](https://docs.google.com/document/d/1bcMK0layzDCiKmpdIB7gShMv7nuqw3TkxUeLcxx91VU/edit#)), and we'd like to include co-chairs and tech leads.  So if you are interested, please reach out to me ([@Heba](https://cloud-native.slack.com/team/UQ93GH72N)).

**Comment by rumpl** [comment]
Hello all, software enginner at Docker and maintainer of moby and runwasi, I would love to help with the working group

**Comment by helayoty** [comment]
FYI.
[Latest draft proposal](https://docs.google.com/document/d/1bcMK0layzDCiKmpdIB7gShMv7nuqw3TkxUeLcxx91VU/edit#) (Same link as before).
Additional discussion happening [here](https://cloud-native.slack.com/archives/C056EDRH4PJ) ([#wg-wasm](https://cloud-native.slack.com/archives/C056EDRH4PJ) slack channel)

Thanks!
