### ISSUE TITLE
paper: Edge Native Application Design Behaviors Whitepaper

### ISSUE THREAD

**Issue by clubanderson** [cncf/tag-runtime#73]
Authors:
Andy Anderson, KubeStellar / IBM Research
Frank Brockners, Cisco Systems
Joel Roberts, Cisco Systems

Reviewers:
Brandon Wick, Aarna Networks
Herve Muyal, Cisco Systems
Tomoya Fujita, Sony
R. Prakash, eOTF

Published: DATE
[Presentation Materials](https://docs.google.com/presentation/d/1abj69EptEaZrYaTymnxGyooVNF57CIWYiD_jCN6qu8U/edit?usp=sharing)

Objective
Building on the [Edge Native Application Principles white paper](https://www.cncf.io/wp-content/uploads/2023/03/CNCF_WhitepaperReport_23.pdf), developed by the IoT Edge Working Group (originally published January 17, 2023), this supplemental paper shows how these principles can be translated into practice by recommending design behaviors for developing applications for edge environments.

Edge native application design builds on cloud native application design (see e.g., “[Architecting Applications for Kubernetes](https://www.digitalocean.com/community/tutorials/architecting-applications-for-kubernetes)'' or “[Twelve-Factor App methodology](https://12factor.net/)”). However, several qualities of the edge and the cloud differ. Consequently, edge native application design includes several cloud native design principles and expands them accordingly. The paper was developed by the IoT Edge Working Group and may be expanded and / or edited in the future.

link: https://docs.google.com/document/d/1Ehgrq5ws7xQl5CqUIibSZMjLtAO0Sbe5SGf590U6ImA/edit?pli=1

**Comment by brockners** [comment]
Quick update on the current status of the draft
(see https://docs.google.com/document/d/1Ehgrq5ws7xQl5CqUIibSZMjLtAO0Sbe5SGf590U6ImA/edit?pli=1)
All current comments in the main body of the document have been addressed.
The final WG-level review of the document requested as an agenda item for the next IOT WG meeting on Aug 23, 2023 (@kate-goldenring)

**Comment by joerober** [comment]
Update - Final review and comments completed in WG meeting 23 Aug 2023. Final version has been submitted and received by the CNCF marketing team for creating paper. This includes request to publish prior to KubeCon North America.

**Comment by raravena80** [comment]
@joerober checking in on this too. Has the paper been published?

**Comment by kate-goldenring** [comment]
@raravena80 CNCF marketing is working on the formatting now. In our meeting today, we got an update that timeline is looking like it should be published by KubeCon NA.

**Comment by joerober** [comment]
CNCF Blog post: https://www.cncf.io/blog/2024/01/25/edge-native-design-behaviors-explained/
Whitepaper posted here: https://www.cncf.io/reports/edge-native-application-design-behaviors-whitepaper/
